@startuml
'https://plantuml.com/component-diagram


package "UI" {
  HTTP - [Client360 Search]
}

node "Backend App" {
   [Graphql]
   [SpringBoot]
}

node "ION Analytics API" {
  [Individual API]
  [Intelligence API]
}


node "Other Sources" {
  [LinkedIn Profiles]
  [Sales Force]
  [Kimble]
  [Email Communication]
}

node "Search" {
  Crawler - [Selenium/BeautifulSoup]
  [Client360 Search] ----->Crawler
}

database "Postgres" {
frame "client360" {
    [Data]
  }
}


[Client360 Search] ---> [Graphql]
[Graphql] -> [SpringBoot]
[SpringBoot] ---> [Intelligence API]
[SpringBoot] ---> [Individual API]
[Selenium/BeautifulSoup] -----> [LinkedIn Profiles]
[Selenium/BeautifulSoup] -----> [Sales Force]
[Selenium/BeautifulSoup] -----> [Kimble]
[Selenium/BeautifulSoup] -----> [Email Communication]
[Client360 Search] -> [Data]
@enduml